### ISSUE TITLE
Ubuntu, firefox installed from deb doesn't seem to work.

### ISSUE THREAD

**Issue by stuaxo** [harshadgavali/searchprovider-for-browser-tabs#139]
Hi,
   I'm on Ubuntu 22.04 amd64, Gnome 42.4, with Firefox 105.0.2.

I opened Firefox, that has lots of tabs, but typing part of the name of any of them doesn't seem to show any results.
I have tried reinstalling the firefox extension from the firefox extension page but it doesn't seem to help.

Cheers
Stuart

**Comment by stuaxo** [comment]
I double checked this + have the addon installed in firefox.

In GNOME looking glass the extension hasn't logged any errors.

Any idea how I can debug this ?

**Comment by harshadgavali** [comment]
Hi,
You need to install 3 components for this to work.
You can see them on [README](https://github.com/harshadgavali/searchprovider-for-browser-tabs#installation).

Could you confirm if after installing all 3 components whether search works?

**Comment by stuaxo** [comment]
Ooh, think I did something silly and didn't install the host connector, will confirm...

**Comment by stuaxo** [comment]
Yep, totally was that - think I had not installed as I'd got lazy when there was no deb.

Using the meson instructions worked great.
