### ISSUE TITLE
Not working on Ubuntu 21.10.

### ISSUE THREAD

**Issue by ceiphr** [harshadgavali/searchprovider-for-browser-tabs#2]
Hello!

I'm on Firefox 96.0b10 (not the snap version, but instead the beta found here: https://launchpad.net/~mozillateam/+archive/ubuntu/firefox-next).

I've installed the GNOME extension and Firefox add-on as instructed and installed the connector from releases.

I'm not seeing any tabs when searching in GNOME. Please let me know how I can troubleshoot this issue.

Thank you for such a great project!

**Comment by harshadgavali** [comment]
Thanks Nice catch!!

Does following commands work?
```
# create link for file from lib64 to lib
sudo mkdir -p /usr/lib/mozilla/native-messaging-hosts/
sudo ln -s /usr/lib{64,}/mozilla/native-messaging-hosts/com.github.harshadgavali.tabsearchproviderconnector.json
```

**Comment by ceiphr** [comment]
That fixed it! Thank you!
