### ISSUE TITLE
Firefox window on secondary monitor not always activated

### ISSUE THREAD

**Issue by bartlibert** [harshadgavali/searchprovider-for-browser-tabs#88]
I have a setup with two monitors where I see the following behaviour when searching for a tab from gnome-shell. Note that the correct tab is always switched to, but Firefox is not activated in the following cases (note: target tab is always on the firefox instance on the secondary monitor):

- Firefox  is on the secondary monitor and not activated
- Firefox is on the secondary monitor, there is also a window on the primary monitor that is not activated

If the window on the secondary monitor is active OR another Firefox window on the primary monitor is active, the firefox window on the secondary monitor is correctly activated.

Gnome-shell version: 42.2
Firefox version: 101.0
Extension version: 4
Connector version: 0.1.1-4 from AUR repo

Running on wayland, but Firefox is using xwayland

**Comment by harshadgavali** [comment]
Can you reproduce this if firefox is wayland native?
If not this might be same issue as https://github.com/harshadgavali/searchprovider-for-browser-tabs/issues/26.

**Comment by bartlibert** [comment]
I also have the same issue with native wayland firefox. If you need any more info or logs, let me know.
